name: Renovate
on:
  workflow_dispatch:
  push:
  
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.0
        with:
          configurationFile: toestreich/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          
